name: learn-github-actions
on: [push]
jobs:
  env-variables:
    runs-on: ubuntu-latest
    env:
      MY_NAME: Polt
    steps:
      - name: Echo the env variable
        run: echo '$MY_NAME was just beaten by $GRANDMASTER'
        env:
          GRANDMASTER: Eddy
