name: learn-github-actions
on:
  push:
    branches:
      main
env:
  DAY_OF_WEEK: Monday
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        run: echo "Hello"
