name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env variable
        env:
          MY_NAME: 'Polt'
      - name: Echo the env variable
        run: echo '${{ MY_NAME }}'
