name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      MY_NAME: 'Polt'
    steps:
      - uses: actions/checkout@v3
      - name: Set env variable

      - name: Echo the env variable
        run: echo '${{ env.MY_NAME }}'
