name: test-run
run-name: ${{ github.actor }} studies Github Actions
on: [push]
jobs:
  js_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          ["14", "16"]
    defaults:
      run:
        working-directory: ./js
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm install
          npm test
  python_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: run tests
        run: pytest