name: run-node-file
run-name: ${{ github.actor }} runs JS file
on: [push]
jobs:
  upload-job:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev'}}
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      ENV_CONTEXT: ${{ toJSON(env) }}
    steps:
      - run: echo "The push to dev branch has occured"
      - run: echo $GITHUB_CONTEXT
      - run: echo $ENV_CONTEXT
