name: run-node-file
run-name: ${{ github.actor }} runs JS file
on: [push]
jobs:
  dump_secrets_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_secrets
        run: echo '${{ secrets }}'

  # dump_contexts_to_log:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       id: github_context_step
  #       run: echo '${{ toJSON(github) }}'
  #     - name: Dump job context
  #       run: echo '${{ toJSON(job) }}'
  #     - name: Dump steps context
  #       run: echo '${{ toJSON(steps) }}'
  #     - name: Dump runner context
  #       run: echo '${{ toJSON(runner) }}'
  #     - name: Dump strategy context
  #       run: echo '${{ toJSON(strategy) }}'
  #     - name: Dump matrix context
  #       run: echo '${{ toJSON(matrix) }}'
