name: test-run
run-name: ${{ github.actor }} studies Github Actions
on: [push]
jobs:
  local_test:
    runs-on: ubuntu-latest
    matrix:
      node:
        ["14", "16"]
    working-directory: /.js
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm install
          npm test
