name: run-node-file
run-name: ${{ github.actor }} runs JS file
on: [push]
jobs:
  upload-job:
    runs-on: ubuntu-latest
    if: ${{ github.ref = 'refs/heads/dev'}}
    steps:
      - run: echo "The push to dev branch has occured"
      - run: echo format('Github object -- {0}', ${{ github }})
